avinash201199/DSA-Questions

Linked List/C++/Linked_List.cpp

Please review and revert back for feedback.

Added Linked List in C++ #28

---

Search & Short/Python/Find the duplicate characters in a String

This is the program & Logic, where we can find the duplicate characters in a String using Python..!!

Find the duplicate characters in a String

---

String/Python/first_non_repeating_character_of_string.py

Here's the code for the question:
Given a string s, find the first non-repeating character in it and return its index. If it does not exist, return -1.

Index of first non repeating character in a string

---

Array/C++/012sort.cpp

Adding a common Array problem.

Sorting an Array of 0's, 1's and 2's in O(n) time in C++

---

Search & Short/Python/bubble_short.py

add bubble sort program using Python
[issue number](https://github.com/avinash201199/DSA-Questions/issues/20)

add bubble sort program using Python

---

Search & Short/Java/linearSearchInJAVA.java

please Review this code added my and please let me know if u want me to change something

linear-search-in-java-added

---

Search & Short/Java/binarySearchInJAVA.java

please Review this code added my and please let me know if u want me to change something

binary-search-added-in-java

---

Stacks & Queues/Python/queue.py
Stacks & Queues/Python/stack.py

Added Menu Driven Programs for Stack and Queue Implementation in Python Language

Added Stack and Queues Programs in Python

---

Search & Short/C++/Cyclic_Sort.cpp

Please review this code and please let me know if u want me to change something
fixes #48

Added Cyclic  Sort in C++

---

Linked List/Java/hasCycle.java
Linked List/Java/intersectionNode.java
Linked List/Java/reverseLinkedList.java

Can you review them and merge it on oct 1 😄 ?

Added 3 linked list questions with solution and some explanation in java 

---

Matrix/Python/Largest_Rectangle_Of_0.py

Added finding the largest rectangle of 0 in a matrix of 1 and 0 in O(n^2) in python
fix #11

Added Largest Rectangle Of 0 python

---

Search & Short/Java/bubbleSortInJAVA.java

please Review this code added my and please let me know if u want me to change something😀😀

bubble-sort-added-in-JAVA

---

String/Python/Check Bracketing.py

This add a expression bracketing checker in python.
fix #68 
Let me know if you want me to change something

Added String Bracketing Check Python

---

Array/C++/Rotate_Array.md

I have written code with proper explanation on Left Rotation of an array in C++.

Rotate Array [Code] with explanation

---

Search & Short/Java/Selection.md

I have added selection sort code please check and merge  @avinash201199  
with reference to the issue #64

Selction Sort

---

Array/C++/012sort.cpp
Array/C++/max_subarray_sum.cpp

Added max subarray sum code and problem description in `Array/C++`

Max subarray sum

---

Stacks & Queues/C++/Reverse_Stack_Without_Using_Extra_Space.cpp

Added the code..Please review if any changes need to be made :)

Reverse Stack Without Using Extra Space

---

Two Pointers/C++/4Sum.cpp

I have added  Solution Class of 4 Sum Problem in C++

Add 4 Sum Solution Class

---

Array/Java/Maximum_Product.java
Search & Short/Java/Peak_Index.java

Hey Avinash,
Please review the code and merge the PR on 1st Oct :)
Thanks!

Added Maximum Product of Two Elements in an Array (Java Solution)

---

Stacks & Queues/C++/Stack_Queue.cpp

Please review and revert back for any feedback.
Resolve issue #30 
Thank you!

Added Stack-queue in C++ language

---

Dynamic Programming/C++/Prime_sieve.cpp

Created Prime Sieve

---

Array/C++/containerWithMostWater.cpp
Array/C++/maximumSubarray.cpp
Array/C++/median of sorted array.cpp
Array/C++/threeSum.cpp
BackTracking/C++/NQueen.cpp
BackTracking/C++/permutation.cpp
BackTracking/C++/ratInAMaze.cpp
BackTracking/C++/sudokoSolver.cpp

added backtracking algos like rat in a maze, N queen, sudoku solver etc

added backtracking algos

---

Number theory/C++/Number_Interpretation.cpp

I have contributed to the assigned issue. Please review and let me know if you'd like any changes. Thank you.

Added code for number theory in C++

---

String/Python/Longest Common Prefix

Python Program to find Longest Common Prefix

Create Longest Common Prefix

---

README.md

Updated the HacktoberFest 2021 banner as it appeared missing from such an Amazing repository.
NOTE: This is a valid and verified banner from HacktoberFest Digital Swags and Guidelines. 
Please Merge it if you find it helpful :)

Updated HacktoberFest 2021 banner

---

BST/C++/CheckforBalancedTree.cpp

Please view the code  as well as comments being used to explain the code with respect to the issue #123. I have tried my best to add an explanation wherever I suspect the reader would face difficulty. I have added the problem statement as well.

Code for checking balanced tree in C++ has been added. 

---

Linked List/Java/ExistOrNotInLinkedlist.java

Given an element, how do you find out whether that element exist in a LinkedList or not. If it exist retrieve the position of that element?

Added a Linked list Java Program

---

Array/Python/find_missing_number.ipynb
Search & Short/Python/Reverse_Sort_a_String.ipynb

Reverse string in reverse order

Reverse string in reverse order

---

Array/Java/AlmostSortedArray.java

Added the code that i was assigned #78 
Kindly merge it into the repo.

Almost Sorted Array

---

Binary Tree/Java/BinarySearchTree.java

`Issue numb:` #115
`Question:` Write a Java program to identify the kth smallest element in the binary search tree ?
`my code Output: `
Thank you for assigning the issue @avinash201199 , please guide me if any changes r required :)

Binary Search Tree solution in Java

---

Binary Tree/Java/LinkedListToBinarySearchTree.java

Hi @avinash201199 
Adding code to convert a sorted linked list to a  BST as a part of Hactoberfest 2021.
Please mark it as **hacktoberfest-accepted** if you find it as a valid PR.
Thanks

Add code for Linked List to Binary Search Tree

---

Array/Java/Build Array from Permutation.java

issue #128 build array from permutation

---

Array/C/SumOfTwoArrays.c

Kindly Check it and revert me back if you need any changes. Thank you .

Added the code of Sum of two Arrays using Malloc

---

BST/C++/CheckforBalancedTree.cpp
Graph/C++/BFSandDFS.cpp

I have implemented BFS,DFS functions in a single program  successfully using C++. Please view my explanation(using comments) and code about the different traversals. I have also mentioned the decision to be taken by the user in the comments to print the graph, use BFS or use DFS. Merging this PR successfully would solve issue #159.

BFS and DFS functions implemented successfully in a single program using C++.

---

Array/Python/Inversion Count of arr.py

Create Inversion Count of array in Python by Himanshu 

---

Stacks & Queues/C/infixtopostfix.c

#84 Issue Resolved!
Hey Avinash,
I have put the code as promised.
Hope to do more in this repo!
Regards,
Mukund Deepak

#84 Issue Resolution

---

Dynamic Programming/Java/PascalsTriangle.java

Linked Issue #9
I have pulled the latest commit and I have checked the changes. I have tried my best to write a descriptive code with explanations and diagrams. 
Please review the pull request and merge it labelling `hacktoberfest-accepted`.

Issue #9 Pascal's Triangle

---

BST/C++/binarySearchTree.cpp

Issue - Fixes #23 
I have successfully completed the code for Binary Search Tree in C++
Insertion, Search and Deletion included in the code and proper comments explaining the code available.
Please review and merge it, and let me know if there is any problem.

DSA - Binary Search Tree in C++

---

String/C/Sort an array of string

like to add this string question

Create Sort an array of string

---

Array/C++/stocks_buy_sell.cpp

I have added the stock buy sell probelm with three approaches.

Stock buy Sell 

---

Search & Short/Java/CyclicSort.java

Issue Number : #60
Added cyclic Sort in Java.
@avinash201199 Pls merge this under Hactoberfest label.
Thank you.

Added cyclic Sort in Java

---

Number theory/Python/ATM.py.txt

`Issue numb: ` #147 
`Question: `
Pooja would like to withdraw X $US from an ATM. The cash machine will only accept the transaction if X is a multiple of 5, and Pooja's account balance has enough cash to perform the withdrawal transaction (including bank charges). For each successful withdrawal the bank charges 0.50 $US. Calculate Pooja's account balance after an attempted transaction.
`My Solution: `
https://github.com/syamala27/DSA-Questions/tree/main/Number%20theory/Python
Thanks for assigning the issue @avinash201199 please guide me if any changes are required.

ATM solution in Python

---

Search & Short/C++/Binary Search C++(STL)

Create Binary Search C++(STL)

---

Array/C++/Largest_sum_subarray.cpp

added the question with hint and explaination and approach.

#61 as assigned, resolve 

---

String/Java/LengthofLastWord.java

I code Added for Length of Last Word in Java folder present in Strings.

Lengthof Last Word (Hactoberfest2021)

---

Stacks & Queues/C++/queue.cpp
Stacks & Queues/C++/stack.cpp

Add stack and queue implementation both in Array and Linkedlist method

Add stack and queue implementation

---

String/Python/Menu-Driven Program - Strings Python.py

Menu Driven program for different operations on string entered by User

Create Menu-Driven Program - Strings Python.py

---

Binary Tree/Python/largest_subtree_sum.py

I have added the code for this issue - largest subtree sum in a tree #207 for hacktoberfest-2021. Please review this code and approve this PR.

largest subtree sum

---

String/Java/firstNonRepeatingChar.java

First non-repeating charachter in a string.

Resolving issues #7

---

Dynamic Programming/C++/max_stock_profit.cpp

Hi, I have added the solution to issue #88

Feat: Best Time to Buy and Sell Stock

---

BST/C++/Merge_Two_BST.cpp

Complete C++ code to merge two BSTs in Linear Time and LogN space .
Contains comments to make readability easier along with a sample input.
Contributed under Hacktoberfest21.

Merge two BSTs

---

Stacks & Queues/C++/Remove_All_Adjacent_Duplicates_in_String.cpp

Remove All Adjacent Duplicates in String question added in Stack and Queues

---

Dynamic Programming/C++/Palindrome Partitioning.cpp

Added Palindrome partitioning.cpp

---

Linked List/Java/SymetricTree.java

Plz accept my PR with hacktoberfest2021 ASAP

SymetricTree.java

---

Array/Java/Maximum-Gap.md

I have added three java approaches for the question with comments wherever I though it was necessary.  Thankyou

Maximum Gap Issue #62

---

Graph/C++/Number_of_Provinces.cpp

Resolved Issue #161 
Please merge this branch.

Added Program for Number of Provinces in CPP

---

Search & Short/C++/selection_sort.cpp

Added Selection Sort program in c++.

Selection Sort in c++ added

---

Array/Python/jump-game.py

Added a problem: **JUMP GAME**.
The solution is coded in **Python.**
This closes issue #181 Would like to add a problem: Jump Game.
Could you please accept this and add "hacktoberfest-accepted" label? Thank you. 😄

Add jump-game.py

---

Array/C++/Rotate_Array.md

Change time complexity from O(n^2) to O(n)

Time complexity change to O(n) from o(n^2)

---

BackTracking/Java/Path With Maximum Gold.java

Create Path With Maximum Gold.java

---

Stacks & Queues/C/Stack.c

Added Stack.c in  Stacks & Queues\C folder
Please let me know if you want some changes!

Added Stacks in C language

---

Stacks & Queues/C/Queue.c

Added Queue.c  in \Stacks & Queues\C folder
Let me know if you need some changes!

Added Queues in C language

---

Stacks & Queues/C++/Stack Using Array.cpp

Stack using Array

---

Graph/C++/kahn-algorithm.cpp

Please review the code added and let me know if u want some changes.

Added Kahn Algorithm to find topological order

---

Disjoint Set Union/LongestConsecutiveSequence.cpp

Please review question based on the concept of Disjoint set Union. 
This is with respect to the issue raised #274 
Please review @avinash201199 .

Longest consecutive sequence (Union Find)

---

Linked List/C++/PalindromeLinkedList.cpp

Hello here I have added my code for palindrome linked list in C++. Let me know if I need to do some changes.

Added Code for Palindrome Linked List

---

Search & Short/Javascript/SelectionSort.js

Added Javascript Selection Sort Algo

---

Matrix/C++/MatrixMultiplication.cpp

Added a program in C++ to multiply two matrices.
Please review and merge.
Issue resolved: #33 
Thank you!

Added a matrix multiplication program in C++.

---

BackTracking/C++/sudokoSolver.cpp

Added a test case if answer doesn't exists

updated code

---

BackTracking/word_break.md

explain the word break problem

explain word break problem

---

Array/C++/largest element in array

It's a simple program to find maximum  element in an array.

Create largest element in array

---

Dynamic Programming/C++/Maximu Square in Binary Matrix.cpp

Issue #270 has been resolved. Do let me know if changes are required.

Code added for issue #270

---

Array/C++/kth_maximum_and_minimum.cpp

I have given the proper solution with appropriate comments and explanation please merge this and tag it under hacktober fest accepted.
solution for Issue #303

Solution for the issue #303 problem Kth maximum and minimum

---

Array/Java/Maximum_Product_Adjacent_Elements.java

Write a program that reads an array of ints and outputs the maximum product of two adjacent elements in the given array of numbers.
Input data format
The first line of the input contains the number of elements in the array.
The second line contains the elements of the array separated by spaces.
```
Sample Input:
3
4 8 5
Sample Output:
```40```
Sample Input:
3
10 8 4
Sample Output:
80

The maximum product of adjacent elements #165

---

Search & Short/C++/Linear Search C++(STL)

#192 
Searches for an element in an array with O(N) Time complexity

Linear Search C++(STL)

---

Dynamic Programming/C++/ClimbingStairs.cpp

@avinash201199, This PR solves the issue #262

Feat: Dynamic Programming-Climbing Stairs

---

String/Java/KMPStringMatching.java

Hey @avinash201199!
Please add the `hacktoberfest` tag if you merge the PR.
Thank you :)

Added the Knuth Morris Pratt Algorithm (Java)

---

Graph/C++/Bipartite Graph .cpp
Graph/C++/Cycle Detection in DFS .cpp
Graph/C++/Finding No of Connected Components in Graph .cpp
Graph/C++/In-Out Timing .cpp
Graph/C++/Single Source Shortest Path (dfs) .cpp

@avinash201199  Sir I have added some problems on Graphs . Please Merge it .

 Graphs Added

---

Dynamic Programming/C++/longest palindromic subsequence_bottom-up.cpp
Dynamic Programming/C++/longest palindromic subsequence_top-down.cpp

Fixes #387 
Solves problem using :
-Top-down approach
-Bottom-up approach
[HacktoberFest contribution]

Longest palindromic subsequence 

---

Array/C++/length_of_last_word.cpp
Matrix/C++/Matrix.cpp
matrix_multiplication.cpp

 length_of_last_word.cpp

---

Dynamic Programming/C++/Minimum Sum Partition.cpp

I have solved Issue #202 . Do let me know if changes are required.

Added Minimum Sum Partition (C++) 

---

Search & Short/Java/MergeSortArray.java

Add Merge sort using Java
Issue #243

Add merge sort java  (Issue #243)

---

Linked List/C++/Deletion in Linked List.cpp

Deletion of node in Linked List

---

Array/Java/PairWithSumK.java

- Naive approach
- Using Hashset

Solution to find pair with given sum in array

---

Dynamic Programming/C++/Number of Square in Binary Matrix.cpp

I have added code for issue #272 . Please let me know if you require any change.

Code added for issue272

---

Search & Short/C++/Aggressive Cow problem.cpp

I have added Aggressive Cow problem(SPOJ) using binary search with complete explanation(using comments) using C++.
I have also included the problem statement.
Please view all the commits and changes. Merging this PR successfully would close issue #251.

Aggressive Cow problem(SPOJ) using binary search has been added.

---

Array/Java/First Missing Positive.java

Fixes #342 
Given an unsorted integer array nums, return the smallest missing positive integer.
You must implement an algorithm that runs in O(n) time and uses constant extra space.
I have sorted all elements using Cyclic sort and then,
search out first missing element in an array(nums).

Added Java solution for First_missing_positive

---

Dynamic Programming/C++/Best time to buy and sell stock II

Added my fully commented code!
issue[#384](https://github.com/avinash201199/DSA-Questions/issues/384#issue-1014002496) resolved

Best time to buy and sell stock ii

---

String/C++/Remove_common_characters.cpp

Remove Characters that are same in 2 strings

---

Binary Search/Java/Find in Mountain Array.java

Fixes #337 
Given a mountain array mountainArr, return the minimum index such that mountainArr.get(index) == target. If such an index does not exist, return -1.
I have firstly find out the index of max.(peak) element. Lastly, search target element in between 0th index to peak and then peak to last index element using Binary Search.

Added Java solution for Find_in_mountain_array

---

Search & Short/C++/AllocateMinimumNumberOfPages.cpp

Issue: #339
[Binary Search Interview Problem by apimpulse] 
//hacktoberfest2021
Given number of pages in n different books and m students. The books are arranged in ascending order of number of pages. Every student is assigned to read some consecutive books. The task is to assign books in such a way that the maximum number of pages assigned to a student is minimum.
Example :
Input : pages[] = {12, 34, 67, 90}
m = 2
Output : 113
Explanation:
There are 2 number of students. Books can be distributed in following fashion : 
1) [12] and [34, 67, 90]
Max number of pages is allocated to student 2 with 34 + 67 + 90 = 191 pages
2) [12, 34] and [67, 90]
Max number of pages is allocated to student 2 with 67 + 90 = 157 pages 
3) [12, 34, 67] and [90]
Max number of pages is allocated to student 1 with …

Allocate minimum number of pages - Issue: #339

---

Dynamic Programming/C++/SubsetSum.cpp

Add code for SubsetSum Problem #355

---

Linked List/C++/Reverse_knodes.cpp

Reverse Linked List After K Nodes

---

Search & Short/C++/mergesort_half of n space.cpp

the code is written in c++, and the space complexity is only n/2 instead of n.
thank you.

I created mergesort_only use half of n space.cpp in folder Search & Short

---

Search & Short/Java/Smallest greater than target.java

#203
Find smallest letter greater than the target in Java

Find smallest letter greater than the target

---

Stacks & Queues/C++/PostfixEvaluation.cpp

Postfix Evaluation

---

Binary Tree/C++/BinarySearchTreeValidation.cpp

Hi i have added the solution of the above mentioned Problem.
Please Check :)
#354

Binary Search Tree Validation C++

---

String/C/Palindrome using stacks

A c program which can check whether the given string is a palindrome or not by using the concept of stacks .

Palindrome using stacks

---

Binary Tree/C++/Trees/Binary Tree/Binary_Tree_All_in_One.cpp

In this cpp file I have coded almost all concepts of Binary Tree.

Added Binary Tree All in One code(800+ lines)

---

Search & Short/C++/MergeSort.cpp

 MergeSort.cpp

---

Search & Short/Java/ExponentialSearch.java

Add Exponential Search using Java
Issue : #246

Add exponential search Java (Issue: #246)

---

BackTracking/C++/Backtracking_Using_Bitmask.cpp

Issue #240 resolved( Backtracing Using Bitmasking in C++)
Please review it to make any changes  :))

Backtracing Using Bitmasking

---

Linked List/C++/Detection and removal of a cycle.cpp

Added Detection and Removal of a cycle problem in cpp.

Detection and removal of a cycle

---

Heap/C++/median_in_a_stream.cpp

Median in a stream problem added

---

Stacks & Queues/C++/Optimized_pairsum.cpp

Pair sum using unordered set

---

Binary Tree/Java/DiameterOfBinaryTree.java

Diameter of a binary tree

---

Array/C++/pair_sum.cpp

hii, I have solved this issue. please do let me know if conflict or problem is there.

 Pair Sum Problem solved in unordered array

---

Array/Java/MajorityElement.java

Majority element in an array

---

Array/Java/Jewels_and_Stones.java

#254 Added Jewels & Stones Solution (Java)
I have added the solution along with full problem statement & sample test cases.

Solved #254  Added Jewels & Stones Solution (Java)

---

Array/C++/Next_Permutation.cpp
Heap/C++/median_in_a_stream.cpp

Next Permutation

---

Search & Short/C++/quick_sort.cpp

a simple c++ program for sorting arrays using quick sort

create quick sort

---

String/Java/longestCommonPrefix.java

Resolving issue #290. Kindly merge the pr. Thank you.

LongestCommonPrefix

---

Array/C/Array implementation in C/README.MD
Array/C/Array implementation in C/deletion.c
Array/C/Array implementation in C/insertion.c
Array/C/Array implementation in C/main.c
Array/C/Array implementation in C/traversal.c

After carefully going through the repo, I was able to see DSA with C language under Array directory is empty. I want to contribute it using some of my knowledge. Added REAEDME.MD file for clear understanding.
I'll be implementing array using C language with all set of operations -
traversing
insertion
deletion
Please tag this PR under 'hacktober fest 2021'

DSA : Array implementation in C 

---

Matrix/C++/strassens algorithm.cpp

Strassen's Algorithm for matrix multiplication

Strassen's Algorithm for matrix multiplication

---

Binary Tree/C++/traversals.cpp

Add these different type of traversals
1. preorder
2. postorder
3. inorder
4. level order
5. zig-zag
Merge these changes

Add different travesals in Binary Tree folder

---

Prime/Sieve.cpp

Sieve implemented in C++

---

Dynamic Programming/C++/DP- Longest Strictly Increasing Subsequence

#378 
This is my code for https://practice.geeksforgeeks.org/problems/longest-increasing-subsequence-1587115620/1

Create DP- Longest Strictly Increasing Subsequence

---

Array/C++/Kadens Algorithm.cpp

I have added kadens Algorithm with comment.

Create Kadens Algorithm.cpp

---

Array/C++/sieveoferatosthenes.cpp

#1 Sieve of Eratosthenes Used to print all prime numbers smaller than or equal to n

Used to print all prime numbers smaller than or equal to n

---

Matrix/Java/Sort Boundary Elements of 2 Dimensional Matrix.java

Java program to sort and print the boundary elements of a Two Dimensional Matrix

Create Sort and Print Boundary Elements 2D Matrix

---

Graph/Python/DFS.py

Program in Python to perform Depth First Search Traversal

Create Depth First Search (DFS) Traversal

---

Search & Short/Javascript/quick_sort.js

**Changes**
- Added `quick_sort.js`.
- resolves #460

QuickSort JavaScript Code Added

---

BST/C++/BST_Search_Element.cpp

This Program will display elements between 2 numbers given by the user.

Display Element Between a Range in BST.

---

Array/Java/ShortestSubArray.java

ShortestSubArray.java  is added inside the Java folder which is present inside the Array folder under the main branch.
Fixex #242

Shortest Subarray with Sum at Least K

---

BST/Python/Binary_Search_tree.py

issue no : #257
@avinash201199

Added Binary search tree in python program

---

Stacks & Queues/C++/trapping_rainwater_problem.cpp

The famous rainwater trapping problem is added in stacks and queues folder

rainwater-trapping-problem-added

---

Binary Tree/C++/Levelorder.cpp

prints level order of binary tree

---

Bubble sort

Create Bubble sort

---

Linked List/C++/Insertion in Doubly Linked List

It includes :-
- Insertion at Tail in Doubly Linked List
- Insertion at Head in Doubly Linked List

Create Insertion in Doubly Linked List

---

Linked List/Deletion in Doubly Linked List

It includes:-
- Deletion of Elements from Position in Doubly Linked Lists.
- Deletion at Head in Doubly Linked Lists.

Create Deletion in Doubly Linked List

---

Linked List/C++/Insertion in Circular List

This includes :-
-  Insertion at Tail in Circular Linked List.
- Insertion at Head in Circular Linked List.

Create Insertion in Circular List

---

Linked List/Deletion in Circular Linked List

This includes:-
- Delete from position in Circular Linked List.
- Delete from head in Circular Linked List.

Create Deletion in Circular Linked List

---

Linked List/C/circular.c

Added another types of linked list

Create Circular linked list

---

Linked List/Java/LinkedListAndIsCyclic.java

1.   Implementation of linkedList Class (Node, data)
2.   Append Method: add value in the end of list
3.   Prepend Method: add value in the beginning of list
4.   deleteByValue Mathod: delete value from list
5.   isCyclicLinkedList Method:  Check if linkedList is cyclic in nature

Impl of LinkedList, basic methods & isCyclic method #576

---

String/Java/LongestSubString.java

Find the length of the longest substring without repeating characters in Java

Length of Longest Sub String #575

---

Implementation of stl/List.h

I added the implementation of stl list included the List:;iterator and the member functions.
@avinash201199 , I would be very happy to see it merged.
Thank you so much!!!

stl list implimention #582
